# Generated by Django 2.2.3 on 2019-08-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_1',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name='选择1'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_2',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name='选择2'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_3',
            field=models.IntegerField(blank=True, max_length=3, null=True, verbose_name='选择3'),
        ),
    ]
