# Generated by Django 2.2.3 on 2019-08-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_vote', '0002_auto_20190801_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='option_2',
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_3',
        ),
        migrations.AlterField(
            model_name='option',
            name='option_1',
            field=models.IntegerField(choices=[(0, '未选择、弃票'), (1, '支持'), (2, '不支持')], default=0, verbose_name='选项'),
        ),
    ]
