# Generated by Django 2.2.3 on 2019-08-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_vote', '0004_auto_20190801_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='onsupport',
            field=models.IntegerField(blank=True, choices=[(0, '未选择、弃票'), (1, '支持'), (2, '不支持')], default=0, null=True, verbose_name='不支持'),
        ),
        migrations.AlterField(
            model_name='option',
            name='support',
            field=models.IntegerField(blank=True, choices=[(0, '未选择、弃票'), (1, '支持'), (2, '不支持')], default=0, null=True, verbose_name='支持'),
        ),
        migrations.AlterField(
            model_name='option',
            name='waiver',
            field=models.IntegerField(blank=True, choices=[(0, '未选择、弃票'), (1, '支持'), (2, '不支持')], default=0, null=True, verbose_name='弃票'),
        ),
    ]
